# llm.config.yaml
# Project-specific commands for the LLM to execute.
#
# Replace the placeholder commands below with the actual commands
# for your project's technology stack.

version: 1.0

quality_gates:
  # Command to run the entire test suite
  test: "npm test"

  # Command to run the linter, preferably with auto-fix capabilities
  lint: "npm run lint -- --fix"

  # Command to format the entire codebase
  format: "npx prettier --write ."

  # Command for static type checking, if applicable
  type_check: "npm run tsc"

  # Command for a dependency vulnerability scan
  security_scan: "npm audit"

# Paths to exclude from all LLM-initiated scans and edits.
# The core llm/ directory is always excluded by default.
exclude_paths:
  - "dist/"
  - "build/"
  - "node_modules/"
  - "venv/"
  - ".git/" 