# gates.yaml
# Project-specific commands for the LLM quality gates.
# Replace the placeholder commands below with the actual commands for your stack.

version: 1.0

# Command to run the entire test suite
test: "your-test-command --ci"  # e.g., "npm test", "pytest", "go test ./..."

# Command to run the linter with auto-fix capabilities
lint: "your-lint-command --fix"  # e.g., "eslint . --fix", "ruff check . --fix"

# Command to format the codebase
format: "your-format-command"     # e.g., "prettier --write .", "black ."

# Static type checking
type_check: "your-type-check-command"  # e.g., "tsc", "mypy ."

# Dependency vulnerability scan
security_scan: "your-security-scan-command"  # e.g., "npm audit", "pip-audit" 